# Generated by Django 5.1.2 on 2024-10-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
