# Generated by Django 5.0.4 on 2024-09-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=250)),
                ('tel', models.CharField(default=0, max_length=8)),
                ('cita', models.DateField()),
                ('hora', models.TimeField()),
                ('servicio', models.CharField(max_length=250)),
                ('barbero', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
