# Generated by Django 5.1.2 on 2024-10-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0002_rename_fecha_cita_fecha_reserva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='fecha_vencimiento',
        ),
        migrations.AddField(
            model_name='cita',
            name='cita_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
