# Generated by Django 5.1.2 on 2024-10-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0003_remove_cita_fecha_vencimiento_cita_cita_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='reserva_cita',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
