# Generated by Django 5.1.2 on 2024-10-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0004_cita_reserva_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='reserva_cita',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
