# Generated by Django 5.1.2 on 2024-10-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0006_remove_cita_cita_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='barbero',
            field=models.CharField(max_length=200, verbose_name='barbero'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='cita',
            field=models.DateField(verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='cliente',
            field=models.CharField(max_length=250, verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.IntegerField(default=0, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha_reserva'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(verbose_name='hora'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='reserva_cita',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(max_length=250, verbose_name='servicio'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tel',
            field=models.CharField(default=0, max_length=8, verbose_name='telefono'),
        ),
    ]
