# Generated by Django 5.1.1 on 2024-10-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('foto', models.ImageField(blank=True, default='S/F', null=True, upload_to='productos/')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Estilos',
        ),
    ]
